name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8_x86
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x86
    - name: Build with Maven
      run: mvn -B package --file pom.xml
