name: Maven Release Package Deployment

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8_x86
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x86
    - name: Build & Deploy with Maven
      run: mvn -B deploy --file pom.xml -Dregistry=https://maven.pkg.github.com/Enfernuz -Dtoken=${{secrets.GITHUB_TOKEN}}
